name: CI
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.4.1'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile
          yarn add prettier eslint

      - name: Run linters
        run: |
          cp config/database.yml.sample config/database.yml
          cp .env.sample .env
          bundle exec rubocop --parallel
          prettier
          eslint

      - name: Run security checks
        run: |
          cp config/database.yml.sample config/database.yml
          cp .env.sample .env
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: open_condo
          POSTGRES_DB: open_condo_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.4.1'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: open_condo
        run: |
          cp config/database.yml.sample config/database.yml
          cp .env.sample .env
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec