name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
    env:
      # The hostname used to communicate with the PostgreSQL service container
      POSTGRES_HOST: localhost
      # The default PostgreSQL port
      POSTGRES_PORT: 5432
services:
  # Label used to access the service container
  postgres:
    # Docker Hub image
    image: postgres
    # Provide the password for postgres
    env:
      POSTGRES_PASSWORD: postgres
    # Set health checks to wait until postgres has started
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
        ports:
    # Maps tcp port 5432 on service container to the host
    ports:
      - 5432:5432